@baseUrl = http://localhost:3000

@authToken = {{diretor_authenticate_user.response.body.token}}

@authMember = {{member_authenticate_user.response.body.token}}

###

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Bruce Wayne",
  "email": "bruce.wayne@teamflow.com",
  "password": "securepassword",
  "role": "MEMBRO"
}

###

# @name diretor_authenticate_user
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "diretor@teamflow.com",
  "password": "senhaforte123"
}

###

# @name member_authenticate_user
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "sarah.connor@teamflow.com",
  "password": "newsecurepassword"
}

###

# @name get_users

GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_user_by_id
GET {{baseUrl}}/users/151aaa22-20b6-4bea-91a2-b467acca93b6
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_profile
GET {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{authMember}}

###

# @name update_profile
PUT {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{authMember}}

{
  "password": "newsecurepassword"
}

###

# @name update_user
PUT {{baseUrl}}/users/151aaa22-20b6-4bea-91a2-b467acca93b6
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "isActive": true
}

###

# @name deactivate_user
PATCH {{baseUrl}}/users/151aaa22-20b6-4bea-91a2-b467acca93b6/deactivate
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "isActive": false
}

###

# @name create_sector
POST {{baseUrl}}/sectors
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Front-End",
  "description": "Setor responsável pelo desenvolvimento do front-end."
}

###

# @name get_sectors
GET {{baseUrl}}/sectors
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_sector_by_id
GET {{baseUrl}}/sectors/c09e3605-928d-4b60-b057-6a95ce4ecdad
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_sector
PUT {{baseUrl}}/sectors/c09e3605-928d-4b60-b057-6a95ce4ecdad
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Back-End",
  "description": "Setor responsável pelo desenvolvimento do back-end atualizado.",
  "isActive": true
}

###

# @name delete_sector
DELETE {{baseUrl}}/sectors/c09e3605-928d-4b60-b057-6a95ce4ecdad
Authorization: Bearer {{authToken}}

###

# @name list_or_filter_sectors
GET {{baseUrl}}/sectors/filter?name=back
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_project
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Projeto W",
  "description": "Descrição do Projeto X",
  "sector": "c09e3605-928d-4b60-b057-6a95ce4ecdad"
}

###

# @name get_projects
GET {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_project
PUT {{baseUrl}}/projects/59211c9e-8f80-41f4-9530-542549320901
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Projeto X Atualizado",
  "description": "Descrição atualizada do Projeto X",
  "isActive": true
}

###

# @name add_member_to_project
PUT {{baseUrl}}/projects/59211c9e-8f80-41f4-9530-542549320901/members/6770df54-76b9-4e9e-b368-c88a68511cae
Authorization: Bearer {{authToken}}

###

# @name delete_member_from_project
DELETE {{baseUrl}}/projects/c94a1b99-18f5-46c0-a61f-9d384f65e5c2/members/7179e6d9-94a6-4b83-ae98-7fecb2b0dee4
Authorization: Bearer {{authToken}}

###

# @name view_my_projects
GET {{baseUrl}}/projects/my-projects
Authorization: Bearer {{authMember}}

###

# @name delete_project
DELETE {{baseUrl}}/projects/59211c9e-8f80-41f4-9530-542549320901
Authorization: Bearer {{authToken}}